# Header
menu:
 主页: /
 所有文章: /archives
 # 随笔: /tags/随笔

# SubNav
subnav:
 github: "https://github.com/OOP-Code-Bunny/"       //github地址
 weibo: "http://weibo.com/p/1005052438739075/home"  //微博地址
 rss: "#"                                           //订阅
 zhihu: "#"                                         //知乎地址
 #douban: "#"                                       //下面这些前面带#的,就不显示在主页上,如果有账号,就可以打开
 #mail: "#"
 #facebook: "#"
 #google: "#"
 #twitter: "#"
 #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "https://avatars1.githubusercontent.com/u/11350373?v=3&s=460"     //设置头像图片
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true                                                             //使用'多说'评论
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
 我的github: https://github.com/OOP-Code-Bunny/                           //自定义友情链接
 周孝刚: https://github.com/a5635268/
 王麟: http://kingarthas37.github.io/
 郑印: https://github.com/zhengyin/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 虽然咸鱼翻身还是咸鱼,但至少可以变得好吃一点                                   //关于我介绍

duoshuo_shortname: codebunny                                             //多说域名,后面再解释